/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import JAVA.Conexion;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naga
 */
public class Pincipal extends javax.swing.JFrame {
    private int x;
    private int y;
    private int id;
    private Connection conn;
    private boolean maximizado=false;
    private boolean editar=false;
    DefaultTableModel modeloRegistro;
    DefaultTableModel modeloUsuario;
    DefaultTableModel modeloPrestamo;

    /**
     * Creates new form Pincipal
     */
    public Pincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jPanel_Top = new javax.swing.JPanel();
        jLabel_cerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_registros = new javax.swing.JLabel();
        jLabel_prestamos = new javax.swing.JLabel();
        jLabel_login = new javax.swing.JLabel();
        jLabel_usuarios = new javax.swing.JLabel();
        jLabel_minimixar = new javax.swing.JLabel();
        jPanel_Bottom = new javax.swing.JPanel();
        jPanel_conexion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jTextField_password = new javax.swing.JTextField();
        jLabel_desconectar = new javax.swing.JLabel();
        jLabel_conectar = new javax.swing.JLabel();
        jPanel_registros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_registros = new javax.swing.JTable();
        jLabel_delRegistro = new javax.swing.JLabel();
        jLabel_editRegistro = new javax.swing.JLabel();
        jLabel_addRegistro = new javax.swing.JLabel();
        jPanel_prestamo = new javax.swing.JPanel();
        jLabel_addPrestamo = new javax.swing.JLabel();
        jLabel_delPrestamo = new javax.swing.JLabel();
        jLabel_editPrestamo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_prestamo = new javax.swing.JTable();
        jPanel_users = new javax.swing.JPanel();
        jLabel_editUsuario = new javax.swing.JLabel();
        jLabel_delUsuario = new javax.swing.JLabel();
        jLabel_addUsuario = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        jPanel_Top.setBackground(new java.awt.Color(111, 236, 111));
        jPanel_Top.setMinimumSize(new java.awt.Dimension(800, 193));
        jPanel_Top.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_TopMouseDragged(evt);
            }
        });
        jPanel_Top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_TopMousePressed(evt);
            }
        });

        jLabel_cerrar.setBackground(new java.awt.Color(0, 204, 102));
        jLabel_cerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cerrar.setText("X");
        jLabel_cerrar.setOpaque(true);
        jLabel_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cerrarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("YukiTeca");

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Documents\\estudio\\4_2o\\Interfaces\\tema5\\PE7\\cat.png")); // NOI18N

        jLabel_registros.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_registros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_registros.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registros.setText("Registros");
        jLabel_registros.setEnabled(false);
        jLabel_registros.setOpaque(true);
        jLabel_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registrosMouseClicked(evt);
            }
        });

        jLabel_prestamos.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_prestamos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_prestamos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_prestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_prestamos.setText("Préstamos");
        jLabel_prestamos.setEnabled(false);
        jLabel_prestamos.setOpaque(true);
        jLabel_prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_prestamosMouseClicked(evt);
            }
        });

        jLabel_login.setBackground(new java.awt.Color(0, 204, 102));
        jLabel_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_login.setText("Login");
        jLabel_login.setOpaque(true);
        jLabel_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_loginMouseClicked(evt);
            }
        });

        jLabel_usuarios.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_usuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_usuarios.setText("Usuarios");
        jLabel_usuarios.setEnabled(false);
        jLabel_usuarios.setOpaque(true);
        jLabel_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_usuariosMouseClicked(evt);
            }
        });

        jLabel_minimixar.setBackground(new java.awt.Color(0, 204, 102));
        jLabel_minimixar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_minimixar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimixar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimixar.setText("_");
        jLabel_minimixar.setOpaque(true);
        jLabel_minimixar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimixarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TopLayout = new javax.swing.GroupLayout(jPanel_Top);
        jPanel_Top.setLayout(jPanel_TopLayout);
        jPanel_TopLayout.setHorizontalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_TopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_minimixar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_TopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TopLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_TopLayout.createSequentialGroup()
                        .addComponent(jLabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel_prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel_TopLayout.setVerticalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TopLayout.createSequentialGroup()
                .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_minimixar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel_Bottom.setMinimumSize(new java.awt.Dimension(800, 295));
        jPanel_Bottom.setLayout(new java.awt.CardLayout());

        jPanel_conexion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Contraseña:");

        jTextField_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_usuario.setText("root");

        jTextField_password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel_desconectar.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_desconectar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_desconectar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_desconectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_desconectar.setText("Desconectar");
        jLabel_desconectar.setOpaque(true);
        jLabel_desconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_desconectarMouseClicked(evt);
            }
        });

        jLabel_conectar.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_conectar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_conectar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_conectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_conectar.setText("Conectar");
        jLabel_conectar.setOpaque(true);
        jLabel_conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_conectarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_conexionLayout = new javax.swing.GroupLayout(jPanel_conexion);
        jPanel_conexion.setLayout(jPanel_conexionLayout);
        jPanel_conexionLayout.setHorizontalGroup(
            jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_conexionLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_conexionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel_conexionLayout.setVerticalGroup(
            jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_conexionLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel_Bottom.add(jPanel_conexion, "card2");

        jPanel_registros.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        jTable_registros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_registros.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_registros.setOpaque(false);
        jTable_registros.setSelectionBackground(new java.awt.Color(111, 236, 111));
        jScrollPane1.setViewportView(jTable_registros);

        jLabel_delRegistro.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_delRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_delRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_delRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_delRegistro.setText("Eliminar");
        jLabel_delRegistro.setOpaque(true);
        jLabel_delRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_delRegistroMouseClicked(evt);
            }
        });

        jLabel_editRegistro.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_editRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_editRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_editRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_editRegistro.setText("Editar");
        jLabel_editRegistro.setOpaque(true);
        jLabel_editRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_editRegistroMouseClicked(evt);
            }
        });

        jLabel_addRegistro.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_addRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_addRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_addRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_addRegistro.setText("Añadir");
        jLabel_addRegistro.setOpaque(true);
        jLabel_addRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_addRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registrosLayout = new javax.swing.GroupLayout(jPanel_registros);
        jPanel_registros.setLayout(jPanel_registrosLayout);
        jPanel_registrosLayout.setHorizontalGroup(
            jPanel_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registrosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(jPanel_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_delRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_editRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_addRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel_registrosLayout.setVerticalGroup(
            jPanel_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addGroup(jPanel_registrosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel_addRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel_editRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_delRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel_Bottom.add(jPanel_registros, "card3");

        jPanel_prestamo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_addPrestamo.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_addPrestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_addPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_addPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_addPrestamo.setText("Añadir");
        jLabel_addPrestamo.setOpaque(true);
        jLabel_addPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_addPrestamoMouseClicked(evt);
            }
        });

        jLabel_delPrestamo.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_delPrestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_delPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_delPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_delPrestamo.setText("Eliminar");
        jLabel_delPrestamo.setOpaque(true);
        jLabel_delPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_delPrestamoMouseClicked(evt);
            }
        });

        jLabel_editPrestamo.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_editPrestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_editPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_editPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_editPrestamo.setText("Editar");
        jLabel_editPrestamo.setOpaque(true);
        jLabel_editPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_editPrestamoMouseClicked(evt);
            }
        });

        jTable_prestamo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_prestamo.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_prestamo.setSelectionBackground(new java.awt.Color(111, 236, 111));
        jScrollPane2.setViewportView(jTable_prestamo);

        javax.swing.GroupLayout jPanel_prestamoLayout = new javax.swing.GroupLayout(jPanel_prestamo);
        jPanel_prestamo.setLayout(jPanel_prestamoLayout);
        jPanel_prestamoLayout.setHorizontalGroup(
            jPanel_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_prestamoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(jPanel_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_addPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_editPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_delPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel_prestamoLayout.setVerticalGroup(
            jPanel_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_prestamoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel_addPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel_editPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_delPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        jPanel_Bottom.add(jPanel_prestamo, "card5");

        jPanel_users.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_editUsuario.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_editUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_editUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_editUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_editUsuario.setText("Editar");
        jLabel_editUsuario.setOpaque(true);
        jLabel_editUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_editUsuarioMouseClicked(evt);
            }
        });

        jLabel_delUsuario.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_delUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_delUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_delUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_delUsuario.setText("Eliminar");
        jLabel_delUsuario.setOpaque(true);
        jLabel_delUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_delUsuarioMouseClicked(evt);
            }
        });

        jLabel_addUsuario.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_addUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_addUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_addUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_addUsuario.setText("Añadir");
        jLabel_addUsuario.setOpaque(true);
        jLabel_addUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_addUsuarioMouseClicked(evt);
            }
        });

        jTable_usuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_usuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_usuarios.setSelectionBackground(new java.awt.Color(111, 236, 111));
        jScrollPane3.setViewportView(jTable_usuarios);

        javax.swing.GroupLayout jPanel_usersLayout = new javax.swing.GroupLayout(jPanel_users);
        jPanel_users.setLayout(jPanel_usersLayout);
        jPanel_usersLayout.setHorizontalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usersLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_delUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_addUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_editUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel_usersLayout.setVerticalGroup(
            jPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_usersLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel_addUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel_editUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_delUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        jPanel_Bottom.add(jPanel_users, "card6");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayout.createSequentialGroup()
                    .addComponent(jPanel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 310, Short.MAX_VALUE)))
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                    .addGap(0, 194, Short.MAX_VALUE)
                    .addComponent(jPanel_Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //metodo para poder cerrar la ventana
    private void jLabel_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cerrarMouseClicked
        //primero cerramos la conexion por seguridad
        try {
            if(conn!=null){
                conn.close();
                conn=null;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel_cerrarMouseClicked

    //metodos para controlar las pestañas de opciones, cambiarles el color y hacerlas visibles
    private void jLabel_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginMouseClicked
        setLblColor(jLabel_login);
        JLabel[] label={jLabel_registros,jLabel_prestamos,jLabel_usuarios};
        JPanel[] panel={jPanel_prestamo,jPanel_registros,jPanel_users};
        resetLbl(label,panel);
        jPanel_conexion.setVisible(true);
    }//GEN-LAST:event_jLabel_loginMouseClicked

    private void jLabel_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registrosMouseClicked
        if(conn!=null){
            setLblColor(jLabel_registros);
            JLabel[] label={jLabel_login,jLabel_prestamos,jLabel_usuarios};
            JPanel[] panel={jPanel_conexion,jPanel_prestamo,jPanel_users};
            resetLbl(label,panel);
            jPanel_registros.setVisible(true);
            rellenaRegistros();
        }
    }//GEN-LAST:event_jLabel_registrosMouseClicked

    private void jLabel_prestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prestamosMouseClicked
        if(conn!=null){
            setLblColor(jLabel_prestamos);
            JLabel[] label={jLabel_login,jLabel_registros,jLabel_usuarios};
            JPanel[] panel={jPanel_conexion,jPanel_registros,jPanel_users};
            resetLbl(label,panel);
            jPanel_prestamo.setVisible(true);
            rellenaPrestamos();
        }
    }//GEN-LAST:event_jLabel_prestamosMouseClicked

    private void jLabel_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_usuariosMouseClicked
        if(conn!=null){
            setLblColor(jLabel_usuarios);
            JLabel[] label={jLabel_login,jLabel_registros,jLabel_prestamos};
            JPanel[] panel={jPanel_conexion,jPanel_prestamo,jPanel_registros};
            resetLbl(label,panel);
            jPanel_users.setVisible(true);
            rellenaUsuarios();
        }
    }//GEN-LAST:event_jLabel_usuariosMouseClicked

    //metodos para poder arrastrar la ventana
    private void jPanel_TopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_TopMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel_TopMousePressed

    private void jPanel_TopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_TopMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanel_TopMouseDragged

    //metodo para minimizar
    private void jLabel_minimixarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimixarMouseClicked
            setVisible(true);
            setExtendedState(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_minimixarMouseClicked

    //metodo para conectar con la base de datos
    private void jLabel_conectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_conectarMouseClicked
        String usuario=jTextField_usuario.getText().trim();
        String pass=jTextField_password.getText().trim();
        if(usuario.length()==0){
            jTextField_usuario.setBackground(Color.RED);
            JOptionPane.showMessageDialog(Pincipal.this, "Falta el usuario");
        }
        /*if(pass.length()==0){
            jTextField_password.setBackground(Color.RED);
            JOptionPane.showMessageDialog(Pincipal.this, "Falta la contraseña");
        }*/
        if(usuario.length()>0/* && pass.length()>0*/){
            Conexion c=new Conexion(usuario,pass);
            conn=c.getConexion();
            if(conn==null){
                JOptionPane.showMessageDialog(Pincipal.this, "Usuario o contraseña incorrectos");
            }
            else{
                limpiaconexion(true);
            }
        }
    }//GEN-LAST:event_jLabel_conectarMouseClicked

    //metodo para desconectar
    private void jLabel_desconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_desconectarMouseClicked
        try {
            if(conn!=null){
                conn.close();
                conn=null;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiaconexion(false);
    }//GEN-LAST:event_jLabel_desconectarMouseClicked

    //borrar item de la bd
    private void jLabel_delRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_delRegistroMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_registros.getSelectedRow();
            int id=(Integer)(modeloRegistro.getValueAt(fila,0));
            try {
                //sql
                PreparedStatement ps=conn.prepareStatement("DELETE FROM item WHERE id=?");
                ps.setInt(1,id);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            rellenaRegistros();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Pincipal.this, "Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jLabel_delRegistroMouseClicked

    //editar item de la bd
    private void jLabel_editRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_editRegistroMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_registros.getSelectedRow();
            id=(Integer)(modeloRegistro.getValueAt(fila,0));
            editar=true;
            Item item=new Item(this,true);
            item.setVisible(true);
            rellenaRegistros();
            editar=false;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Pincipal.this, "Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jLabel_editRegistroMouseClicked

    //añadir item en la bd
    private void jLabel_addRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addRegistroMouseClicked
        Item item=new Item(this,true);
        item.setVisible(true);
        rellenaRegistros();
    }//GEN-LAST:event_jLabel_addRegistroMouseClicked

    //añadir prestamo en la bd
    private void jLabel_addPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addPrestamoMouseClicked
        Prestamo prestamo=new Prestamo(this,true);
        prestamo.setVisible(true);
        rellenaPrestamos();
    }//GEN-LAST:event_jLabel_addPrestamoMouseClicked

    //borrar prestamo en la bd
    private void jLabel_delPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_delPrestamoMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_prestamo.getSelectedRow();
            int id=(Integer)(modeloPrestamo.getValueAt(fila,0));
            try {
                //sql
                PreparedStatement ps=conn.prepareStatement("DELETE FROM prestamo WHERE id=?");
                ps.setInt(1,id);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            rellenaPrestamos();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Pincipal.this, "Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jLabel_delPrestamoMouseClicked

    //editar prestamo en la bd
    private void jLabel_editPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_editPrestamoMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_prestamo.getSelectedRow();
            id=(Integer)(modeloPrestamo.getValueAt(fila,0));
            editar=true;
            Prestamo prestamo=new Prestamo(this,true);
            prestamo.setVisible(true);
            rellenaPrestamos();
            editar=false;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Pincipal.this, "Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jLabel_editPrestamoMouseClicked

    //editar usuario en la bd
    private void jLabel_editUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_editUsuarioMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_usuarios.getSelectedRow();
            id=(Integer)(modeloUsuario.getValueAt(fila,0));
            editar=true;
            Usuario usuario=new Usuario(this,true);
            usuario.setVisible(true);
            rellenaUsuarios();
            editar=false;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Pincipal.this, "Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jLabel_editUsuarioMouseClicked

    //borrar usuario en la bd
    private void jLabel_delUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_delUsuarioMouseClicked
        try{
            //obtenemos el id a borrar
            int fila=jTable_usuarios.getSelectedRow();
            int id=(Integer)(modeloUsuario.getValueAt(fila,0));
            try {
                //sql
                PreparedStatement ps=conn.prepareStatement("DELETE FROM usuario WHERE id=?");
                ps.setInt(1,id);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            rellenaUsuarios();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Pincipal.this, "Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_jLabel_delUsuarioMouseClicked

    //añadir usuario en la bd
    private void jLabel_addUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addUsuarioMouseClicked
        Usuario usuario=new Usuario(this,true);
        usuario.setVisible(true);
        rellenaUsuarios();
    }//GEN-LAST:event_jLabel_addUsuarioMouseClicked

    //rellenar tabla de items
    private void rellenaRegistros(){
        try {
            //modelo
            modeloRegistro = new DefaultTableModel();
            jTable_registros.setModel(modeloRegistro);
            modeloRegistro.addColumn("Id");
            modeloRegistro.addColumn("Nombre");
            modeloRegistro.addColumn("Descripcion");
            modeloRegistro.addColumn("ISBN");
            modeloRegistro.addColumn("Tipo");
            modeloRegistro.addColumn("Localizacion");
            //consulta
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT id,nombre,descripcion,isbn,tipo,localizacion FROM item");
            while(rs.next()){
                Object[] fila = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modeloRegistro.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //rellenar tabla de usuarios
    private void rellenaUsuarios(){
        try {
            //modelo
            modeloUsuario = new DefaultTableModel();
            jTable_usuarios.setModel(modeloUsuario);
            modeloUsuario.addColumn("Id");
            modeloUsuario.addColumn("Nombre");
            modeloUsuario.addColumn("Apellidos");
            modeloUsuario.addColumn("E-mail");
            modeloUsuario.addColumn("Telefono");
            modeloUsuario.addColumn("Direccion");
            modeloUsuario.addColumn("CP");
            modeloUsuario.addColumn("Ciudad");
            modeloUsuario.addColumn("Provincia");
            //consulta
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT id,nombre,apellidos,mail,telefono,direccion,cp,ciudad,provincia FROM usuario");
            while(rs.next()){
                Object[] fila = new Object[9];
                for (int i = 0; i < 9; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modeloUsuario.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //rellenar tabla de prestamos
    private void rellenaPrestamos(){
        try {
            //modelo
            modeloPrestamo = new DefaultTableModel();
            jTable_prestamo.setModel(modeloPrestamo);
            modeloPrestamo.addColumn("Id");
            modeloPrestamo.addColumn("Elemento");
            modeloPrestamo.addColumn("Usuario");
            modeloPrestamo.addColumn("Fecha prestamo");
            modeloPrestamo.addColumn("Fecha devolucion");
            modeloPrestamo.addColumn("Comentarios");
            jTable_prestamo.setDefaultRenderer(Object.class,new MiRender());
            
            //consulta
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT id,id_item,id_uruario,fechaPrestamo,fechaDevolucion,comentarios FROM prestamo");
            while(rs.next()){
                Object[] fila = new Object[6];
                for (int i = 0; i < 6; i++) {
                    if(i==1){
                        fila[i]=getItem(rs.getObject(i+1));
                    }
                    else if(i==2){
                        fila[i]=getUsuario(rs.getObject(i+1));
                    }
                    else{
                        fila[i]=rs.getObject(i+1);
                    }
                }
                modeloPrestamo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //si nos conectamos, poder acceder a las pestañas
    private void limpiaconexion(boolean b){
        jTextField_usuario.setBackground(Color.WHITE);
        jTextField_password.setBackground(Color.WHITE);
        JLabel[] pestanas={jLabel_usuarios,jLabel_registros,jLabel_prestamos};
        for(JLabel j:pestanas){
            j.setEnabled(b);
        }
    }
    
    //metodos para cambiar el color de las pestañas dependiendo de si esta seleccionada o no
    private void setLblColor(JLabel lbl){
        lbl.setBackground(new Color(0,204,102));
    }
    
    private void resetLbl(JLabel[] label,JPanel[] panel){
        for(JLabel lbl:label){
            lbl.setBackground(new Color(111,236,111));
        }
        for(JPanel p:panel){
            p.setVisible(false);
        }
    }
    
    //metodos para compartir informacion con los JDialog
    public Connection getConnection(){
        return conn;
    }
    
    public boolean getEditar(){
        return editar;
    }
    
    public int getId(){
        return id;
    }
    
    //obtenemos el item desde su id para rellenar prestamos
    private Object getItem(Object id){
        Object o=null;
        try {
        //consulta
            Statement st=conn.createStatement();
            ResultSet rsI=st.executeQuery("SELECT CONCAT(nombre,' ',descripcion) AS uno FROM item WHERE id="+id);
            rsI.next();
            o=rsI.getObject(1);
        } catch (SQLException ex) {
            Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return o;
    }
    
    //obtenemos el usuario desde su id para rellenar prestamos
    private Object getUsuario(Object id){
        Object o=null;
        try {
        //consulta
            Statement st=conn.createStatement();
            ResultSet rsI=st.executeQuery("SELECT CONCAT(nombre,' ',apellidos) AS uno FROM usuario WHERE id="+id);
            rsI.next();
            o=rsI.getObject(1);
        } catch (SQLException ex) {
            Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return o;
    }
    
    //clase interna para poder cambiar el color de las celdas de prestamos pasados de fecha
    public class MiRender extends DefaultTableCellRenderer{
        public Component getTableCellRendererComponent(JTable table,
            Object value,
            boolean isSelected,
            boolean hasFocus,
            int row,
            int column)
        {
            super.getTableCellRendererComponent (table, value, isSelected, hasFocus, row, column);
            if(column==4){
                //obtenemos la fecha de entrega y la actual para compararlas
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String entrega=value.toString();
                Date entregaD=null;
                try {
                    entregaD = sdf.parse(entrega);
                } catch (ParseException ex) {
                    Logger.getLogger(Pincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                String[] entregaS=entrega.toString().split("-");
                Date hoy=new Date();
                String[] hoyS=sdf.format(hoy).split(" ");
                //si la fecha de entrega es igual a la actual o ha pasado, cambiamos el color de la celda
                if (((entregaS[0].equals(hoyS[0]) && entregaS[1].equals(hoyS[1]) && entregaS[2].equals(hoyS[2])) 
                    || hoy.compareTo(entregaD)>0))
                {
                    this.setBackground(Color.RED);
                }
            }
            else{
                //reseteamos valores
                this.setBackground(Color.WHITE);
                if(isSelected==true || hasFocus==true){
                    this.setBackground(new Color(111,236,111));
                }
            }
            return this;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_addPrestamo;
    private javax.swing.JLabel jLabel_addRegistro;
    private javax.swing.JLabel jLabel_addUsuario;
    private javax.swing.JLabel jLabel_cerrar;
    private javax.swing.JLabel jLabel_conectar;
    private javax.swing.JLabel jLabel_delPrestamo;
    private javax.swing.JLabel jLabel_delRegistro;
    private javax.swing.JLabel jLabel_delUsuario;
    private javax.swing.JLabel jLabel_desconectar;
    private javax.swing.JLabel jLabel_editPrestamo;
    private javax.swing.JLabel jLabel_editRegistro;
    private javax.swing.JLabel jLabel_editUsuario;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_minimixar;
    private javax.swing.JLabel jLabel_prestamos;
    private javax.swing.JLabel jLabel_registros;
    private javax.swing.JLabel jLabel_usuarios;
    private javax.swing.JPanel jPanel_Bottom;
    private javax.swing.JPanel jPanel_Top;
    private javax.swing.JPanel jPanel_conexion;
    private javax.swing.JPanel jPanel_prestamo;
    private javax.swing.JPanel jPanel_registros;
    private javax.swing.JPanel jPanel_users;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_prestamo;
    private javax.swing.JTable jTable_registros;
    private javax.swing.JTable jTable_usuarios;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_usuario;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
