/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JComboBox;
import javax.swing.JSpinner;

/**
 *
 * @author Naga
 */
public class Prestamo extends javax.swing.JDialog {
    private int x;
    private int y;
    private Connection conn;
    private boolean editar;
    private int id;
    Pincipal p;
    ResultSet rsItem;
    ResultSet rsUsuario;
    /**
     * Creates new form Item
     */
    public Prestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        p=(Pincipal)parent;
        this.conn=p.getConnection();
        this.editar=p.getEditar();
        rellenaRegistros();
        rellenaUsuarios();
        rellenaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_cancelar = new javax.swing.JLabel();
        jLabel_aceptar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner_fPrestamo = new javax.swing.JSpinner();
        jSpinner_fEntrega = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_comentarios = new javax.swing.JTextArea();
        jComboBox_item = new javax.swing.JComboBox<>();
        jComboBox_usuario = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_cancelar.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cancelar.setText("Cancelar");
        jLabel_cancelar.setOpaque(true);
        jLabel_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cancelarMouseClicked(evt);
            }
        });

        jLabel_aceptar.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_aceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_aceptar.setText("Aceptar");
        jLabel_aceptar.setOpaque(true);
        jLabel_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_aceptarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Registro:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Fecha de prestamo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fecha de devolucion:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Comentarios:");

        jSpinner_fPrestamo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinner_fPrestamo.setModel(new javax.swing.SpinnerDateModel());

        jSpinner_fEntrega.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinner_fEntrega.setModel(new javax.swing.SpinnerDateModel());

        jTextArea_comentarios.setColumns(20);
        jTextArea_comentarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea_comentarios.setRows(5);
        jScrollPane1.setViewportView(jTextArea_comentarios);

        jComboBox_item.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(20, 20, 20)
                                .addComponent(jSpinner_fEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner_fPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_item, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_usuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner_fPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner_fEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel2.setBackground(new java.awt.Color(111, 236, 111));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prestamo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_cancelarMouseClicked

    private void jLabel_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_aceptarMouseClicked
        //obtenemos los datos a insertar
        String comentarios=jTextArea_comentarios.getText();
        int idUsuario=getId(jComboBox_usuario,rsUsuario);
        int idItem=getId(jComboBox_item,rsItem);
        String fPrestamo=getFecha(jSpinner_fPrestamo);
        String fEntrega=getFecha(jSpinner_fEntrega);
        //insertamos
        try {
            PreparedStatement ps=null;
            if(editar){
                ps=conn.prepareStatement("UPDATE prestamo SET id_item=?,id_uruario=?,fechaPrestamo=?,"
                        + "fechaDevolucion=?,comentarios=? WHERE id="+id);
            }
            else{
                ps=conn.prepareStatement("INSERT INTO prestamo(id_item,id_uruario,fechaPrestamo,fechaDevolucion,"
                        + "comentarios) VALUES(?,?,?,?,?)");
            }
            ps.setInt(1,idItem);
            ps.setInt(2,idUsuario);
            ps.setString(3,fPrestamo);
            ps.setString(4,fEntrega);
            ps.setString(5,comentarios);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }        
        dispose();
    }//GEN-LAST:event_jLabel_aceptarMouseClicked

    //metodos para desplazar la ventana
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    //si editamos, rellenamos los campos
    private void rellenaCampos() {
        if(editar){
            id=p.getId();
            try {
                Statement st = conn.createStatement();
                String query="SELECT id_item,id_uruario,fechaPrestamo,fechaDevolucion,comentarios "
                + "FROM prestamo "
                + "WHERE id="+id;
                ResultSet rs=st.executeQuery(query);
                rs.next();
                
                int idItem=rs.getInt(1);
                setElement(jComboBox_item,idItem,"item");
                int idUsuario=rs.getInt(2);
                setElement(jComboBox_usuario,idUsuario,"usuario");
                String fechaPrestamo=rs.getString(3);
                setFecha(jSpinner_fPrestamo,fechaPrestamo);
                String fechaDevolucion=rs.getString(4);
                setFecha(jSpinner_fEntrega,fechaDevolucion);
                jTextArea_comentarios.setText(rs.getString(5));
                
            } catch (SQLException ex) {
                Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }
    
    //para rellenar el combobox de registros
    private void rellenaRegistros(){
        try {
            //consulta
            Statement st=conn.createStatement();
            rsItem=st.executeQuery("SELECT id,nombre,descripcion FROM item");
            while(rsItem.next()){
                Object[] fila = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i]=rsItem.getObject(i+1);
                }
                jComboBox_item.addItem(fila[1]+" "+fila[2]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //para rellenar el combobox de usuarios
    private void rellenaUsuarios(){
        try {
            //consulta
            Statement st=conn.createStatement();
            rsUsuario=st.executeQuery("SELECT id,nombre,apellidos FROM usuario");
            while(rsUsuario.next()){
                Object[] fila = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i]=rsUsuario.getObject(i+1);
                }
                jComboBox_usuario.addItem(fila[1]+" "+fila[2]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //obtenemos el id del elemento elegido en el combobox
    private int getId(JComboBox combo,ResultSet rs){
        int id=-1;
        String seleccion=combo.getSelectedItem().toString();
        //buscamos los nombres de producto en el resultser
        try {
            rs.beforeFirst();
            while(rs.next()){
                String currentElement=rs.getString(2)+" "+rs.getString(3);
                //si coinciden, ponemos la marca
                if(seleccion.equals(currentElement)){
                    id=rs.getInt(1);
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    //a partir del id, rellenamos el campo correspondiente para que no aparezca el numero
    private void setElement(JComboBox combo,int id,String campo){
        try {
            //consulta
            Statement st=st=conn.createStatement();
            ResultSet rs;
            if(campo.equals("usuario")){
                rs=st.executeQuery("SELECT nombre,apellidos FROM usuario WHERE id="+id);
            }
            else{
                rs=st.executeQuery("SELECT nombre,descripcion FROM item WHERE id="+id);
            }
            rs.next();
            String cadena=rs.getString(1)+" "+rs.getString(2);
            combo.setSelectedItem(cadena);
        } catch (SQLException ex) {
            Logger.getLogger(Prestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //obtenemos la fecha del spinner
    private String getFecha(JSpinner spinner){
        String fecha="";
        Date dia=(Date) spinner.getValue();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fecha = sdf.format(dia);
        return fecha;
    }
    
    //colocamos la fecha en el spinner
    private void setFecha(JSpinner spinner,String fecha){
        String[] campos=fecha.split("-");
        GregorianCalendar gc=new GregorianCalendar(Integer.parseInt(campos[0]),Integer.parseInt(campos[1]),Integer.parseInt(campos[2]));
        spinner.setValue(gc.getTime());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Prestamo dialog = new Prestamo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_item;
    private javax.swing.JComboBox<String> jComboBox_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_aceptar;
    private javax.swing.JLabel jLabel_cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_fEntrega;
    private javax.swing.JSpinner jSpinner_fPrestamo;
    private javax.swing.JTextArea jTextArea_comentarios;
    // End of variables declaration//GEN-END:variables

    
}
