/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Naga
 */
public class Usuario extends javax.swing.JDialog {
    private int x;
    private int y;
    private Connection conn;
    private boolean editar;
    private int id;
    Pincipal p;
    /**
     * Creates new form Item
     */
    public Usuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        p=(Pincipal)parent;
        this.conn=p.getConnection();
        this.editar=p.getEditar();
        rellenaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_cancelar = new javax.swing.JLabel();
        jLabel_aceptar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_apellidos = new javax.swing.JTextField();
        jTextField_mail = new javax.swing.JTextField();
        jTextField_direccion = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        jTextField_cp = new javax.swing.JTextField();
        jTextField_provincia = new javax.swing.JTextField();
        jTextField_ciudad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(461, 452));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(344, 405));

        jLabel_cancelar.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cancelar.setText("Cancelar");
        jLabel_cancelar.setOpaque(true);
        jLabel_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cancelarMouseClicked(evt);
            }
        });

        jLabel_aceptar.setBackground(new java.awt.Color(111, 236, 111));
        jLabel_aceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_aceptar.setText("Aceptar");
        jLabel_aceptar.setOpaque(true);
        jLabel_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_aceptarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("E-Mail:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Telefono:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CP:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Ciudad:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Provincia:");

        jTextField_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyPressed(evt);
            }
        });

        jTextField_apellidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_apellidosKeyPressed(evt);
            }
        });

        jTextField_mail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_mailKeyPressed(evt);
            }
        });

        jTextField_direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_direccionKeyPressed(evt);
            }
        });

        jTextField_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_telefonoKeyPressed(evt);
            }
        });

        jTextField_cp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_cpKeyPressed(evt);
            }
        });

        jTextField_provincia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_provincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_provinciaKeyPressed(evt);
            }
        });

        jTextField_ciudad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ciudadKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(jLabel_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(20, 20, 20)
                                .addComponent(jTextField_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_nombre)
                            .addComponent(jTextField_apellidos)
                            .addComponent(jTextField_mail)
                            .addComponent(jTextField_provincia)
                            .addComponent(jTextField_ciudad)
                            .addComponent(jTextField_direccion))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel2.setBackground(new java.awt.Color(111, 236, 111));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_cancelarMouseClicked

    private void jLabel_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_aceptarMouseClicked
        //obtenemos los datos a insertar
        String nombre=jTextField_nombre.getText().trim();
        String apellidos=jTextField_apellidos.getText().trim();
        String ciudad=jTextField_ciudad.getText().trim();
        String cp=jTextField_cp.getText().trim();
        String direccion=jTextField_direccion.getText().trim();
        String mail=jTextField_mail.getText().trim();
        String provincia=jTextField_provincia.getText().trim();
        String telefono=jTextField_telefono.getText().trim();
        //comprobamos que sean correctos
        if(nombre.length()==0){
            jTextField_nombre.setBackground(Color.RED);
        }
        if(ciudad.length()==0){
            jTextField_ciudad.setBackground(Color.RED);
        }
        if(apellidos.length()==0){
            jTextField_apellidos.setBackground(Color.RED);
        }
        if(cp.length()==0){
            jTextField_cp.setBackground(Color.RED);
        }
        if(direccion.length()==0){
            jTextField_direccion.setBackground(Color.RED);
        }
        if(mail.length()==0){
            jTextField_mail.setBackground(Color.RED);
        }
        if(provincia.length()==0){
            jTextField_provincia.setBackground(Color.RED);
        }
        if(telefono.length()==0){
            jTextField_telefono.setBackground(Color.RED);
        }
        //insertamos
        if(nombre.length()>0 && ciudad.length()>0 && apellidos.length()>0 && cp.length()>0 && 
                direccion.length()>0 && mail.length()>0 && provincia.length()>0 && telefono.length()>0){
            try {
                PreparedStatement ps=null;
                if(editar){
                    ps=conn.prepareStatement("UPDATE usuario SET nombre=?,apellidos=?,mail=?,telefono=?,"
                            + "direccion=?,cp=?,ciudad=?,provincia=? WHERE id="+id);
                }
                else{
                    ps=conn.prepareStatement("INSERT INTO usuario(nombre,apellidos,mail,telefono,"
                            + "direccion,cp,ciudad,provincia) VALUES(?,?,?,?,?,?,?,?)");
                }
                ps.setString(1,nombre);
                ps.setString(2,apellidos);
                ps.setString(3,mail);
                ps.setString(4,telefono);
                ps.setString(5,direccion);
                ps.setString(6,cp);
                ps.setString(7,ciudad);
                ps.setString(8,provincia);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }        
            dispose();
        }
        
    }//GEN-LAST:event_jLabel_aceptarMouseClicked

    //metodos para poder arrastrar la ventana
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    //metodos para resetear el color de los campos
    private void jTextField_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyPressed
        jTextField_nombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_nombreKeyPressed

    private void jTextField_apellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_apellidosKeyPressed
        jTextField_apellidos.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_apellidosKeyPressed

    private void jTextField_mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_mailKeyPressed
        jTextField_mail.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_mailKeyPressed

    private void jTextField_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_direccionKeyPressed
        jTextField_direccion.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_direccionKeyPressed

    private void jTextField_ciudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ciudadKeyPressed
        jTextField_ciudad.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_ciudadKeyPressed

    private void jTextField_provinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_provinciaKeyPressed
        jTextField_provincia.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_provinciaKeyPressed

    private void jTextField_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telefonoKeyPressed
        jTextField_telefono.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_telefonoKeyPressed

    private void jTextField_cpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cpKeyPressed
        jTextField_cp.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_cpKeyPressed

    //si editamos, rellenamos los campos
    private void rellenaCampos() {
        if(editar){
            id=p.getId();
            try {
                Statement st = conn.createStatement();
                String query="SELECT nombre,apellidos,mail,telefono,direccion,cp,ciudad,provincia "
                + "FROM usuario "
                + "WHERE id="+id;
                ResultSet rs=st.executeQuery(query);
                rs.next();
                jTextField_nombre.setText(rs.getString(1));
                jTextField_apellidos.setText(rs.getString(2));
                jTextField_mail.setText(rs.getString(3));
                jTextField_telefono.setText(rs.getString(4));
                jTextField_direccion.setText(rs.getString(5));
                jTextField_cp.setText(rs.getString(6));
                jTextField_ciudad.setText(rs.getString(7));
                jTextField_provincia.setText(rs.getString(8));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario dialog = new Usuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_aceptar;
    private javax.swing.JLabel jLabel_cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_apellidos;
    private javax.swing.JTextField jTextField_ciudad;
    private javax.swing.JTextField jTextField_cp;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_provincia;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables

    
}
